### PR TITLE
Combined line and bar chart renderer

### PR DESCRIPTION
**Pull request by msp**

### CODE REVIEW

**Comment by msp** [comment]
This is ready to merge. It's built on #11 so review that first.

**Comment by robwebdev** [comment]
@msp I'm having a hard time finding anything constructive to offer in a review of this, it's a bit overwhelming for someone at my level tbh! Maybe you could give me a quick run through at some point?

**Comment by msp** [comment]
@robwebdev - sure, np. Be happy to chat it through. I'm not expecting much feedback with these PRs but it's good practice for me to at least open up the offer. Helps my discipline :)

**Comment by msp** [comment]
@robwebdev I'm gonna merge this as I might try do some housekeeping on the flight and would prefer this in master. We can still review if you like, perhaps on Weds morn?

**Pull request merged**
